<#
   obtain user list who did not have setup MFA, and force setup MFA for users
   pre-requirement : connect to Azure AD
#>

# connect to Azure Active Directory
Connect-MsolService

# obtain users who did not have setup MFA
$users = Get-MsolUser | Where-Object {[string]::IsNullOrEmpty($_.StrongAuthenticationMethods)}

# set MFA option for such users
<#
   Available options:
    TwoWayVoiceMobile : Voice message to mobile phone
    OneWaySMS : Text notification to mobile phone
    TwoWayVoiceOffice : Voice message to office phone
    PhoneAppOTP : One time password generated by mobile app
    PhoneAppNotification : Push notification to mobile app
#>
$mf= New-Object -TypeName Microsoft.Online.Administration.StrongAuthenticationMethod
$mf.MethodType = "PhoneAppOTP"
$mf.IsDefault = $true
$mfa = @($mf)
foreach($u in $users){
	$u.UserPrincipalName
	$u | Set-MsolUser -StrongAuthenticationMethods $mfa
}

